//
//  TodoListModelModels.swift
//  TodoList
//
//  Created by Aleksey Efimov on 30.11.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation
import TaskManagerPackage

enum TodoListModel {
  // MARK: Use cases

  enum Request {
	  struct TaskSelected {
		let indexPath: IndexPath
	  }
    }

    struct Response {
		let data: [SectionWithTasks]

		struct SectionWithTasks {
			let section: Section
			let tasks: [Task]
		}
    }

    struct ViewModel {
		/// Содержит в себе список задач для отображения, разделенные на секции
		let tasksBySections: [Section]

		struct Section {
			let title: String
			let tasks: [Task]
		}

		/// Перечисление представляющее наши задачи для отображения на экране
		enum Task {
			case regularTask(RegularTask)
			case importantTask(ImportantTask)
		}

		/// Обычное задание, содержит только то, что отображается на экране
		struct RegularTask {
			let title: String
			let completed: Bool
		}

		/// Важное задание, содержит только то, что отображается на экране
		struct ImportantTask {
			let title: String
			let completed: Bool
			let deadLine: String
			let priority: String
		}
    }
}
