//
//  LoginModels.swift
//  TodoList
//
//  Created by Aleksey Efimov on 30.11.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

enum LoginModel {
	// MARK: Use cases

	struct Request {
		let login: String
		let password: String
	}

	struct Response {
	}

	struct ViewModel {
		let login: String
		let password: String
	}
}
